### ISSUE TITLE
Port 'number' component to official integration

### ISSUE THREAD

**Issue by adebree** [hesselonline/wallbox#10]
The one feature you made available in this custom addon I was extremely happy to have is the number component for the charge power. I used it primarily in an automation to loadbalance the available power. When the rest of the home was using too much power when charging, the automation lowers the charge power of the Wallbox to prevent the main fuse to pop. 

Unfortunately, that specific number component is not ported (yet?) to the official integration (thx for getting that into HA official addons btw!). Are you planning to add the number component to the official addon, and/or, is there anyway to keep using the custom component now the official addon is there as well?

**Comment by hesselonline** [comment]
Hi,

There is actually a PR outstanding on the official integration which adds this functionality. It just needs enough reviews and approvals to get merged.

Gr.
Hessel
