### ISSUE TITLE
Unexpected error fetching wallbox data: 'status_description'

### ISSUE THREAD

**Issue by maurizioandreotti60** [hesselonline/wallbox#15]
Since a couple of days (al least) the log is filled with a lot of these error messages.
2022-03-22 12:57:43 ERROR (MainThread) [custom_components.wallbox.switch] Unexpected error fetching wallbox data: 'status_description'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/wallbox/switch.py", line 35, in async_update_data
    return await hass.async_add_executor_job(wallbox_updater, wallbox, station)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wallbox/switch.py", line 21, in wallbox_updater
    status_description = data["status_description"].lower()
KeyError: 'status_description'

Restarting HA does not fix the issue.
Actually I have HA versione 2022.3.6 and the latest version of wallbox integration.

**Comment by cliviu74** [comment]
Adding more details to this.

The Wallbox upstream API has removed the statusDescription property from the charger status json response.
The mobile app uses a coded status property called "status". I have mapped a few of the states on my Pulsar Plus as follows:

"status"
  - 181: "Waiting for car demand"
  - null: "Disconnected"
  - 209: "Locked"
  - 161: "Ready"
  - 194: "Charging"

Hope this helps.

**Comment by hesselonline** [comment]
Thnx, it seems that the upstream API changed. There are now only 'id's' included, so we will need to no what all the ID's are to get this running again.

**Comment by hesselonline** [comment]
I think I found it in the source code of the wallbox portal

**Comment by penapena** [comment]
Is there a fix on the way?

**Comment by hesselonline** [comment]
there is a PR on the central HASS github for a fix:
https://github.com/home-assistant/core/pull/68708

It just needs a review and to be merged (might help if you log your issue there, at the HASS github).

**Comment by bagfatnick** [comment]
Thanks for getting it patched so quickly, @hesselonline . 
Are you planning to update patch this repo? As the HASS implementation is still missing the pause switch.

**Comment by hesselonline** [comment]
Yes, I have just updated this repo using the OOTB version as a source with added switch. Please let me know how it works; lets consider it a beta test for adding switch to the hass repo.

**Comment by bagfatnick** [comment]
I've just installed the update. The status description is working. However the pause_resume switch is showing as unavailable.

**Comment by hesselonline** [comment]
Pause resume switch works when the car is charging or paused.

**Comment by bagfatnick** [comment]
I see. In the previous version the resume works from the “scheduled” status. Would that be possible?

**Comment by psadeazevedo** [comment]
> I see. In the previous version the resume works from the “scheduled” status. Would that be possible?

Yes it was possible. The same was reported as well on other HA thread and I guess it would be considered.

**Comment by hesselonline** [comment]
resolved
