### ISSUE TITLE
Quasar Discharge Rate

### ISSUE THREAD

**Issue by jonny772** [hesselonline/wallbox#20]
When using Quasar the max charge rate is limited to 6 to 32 A whereas this has an accessible input range from -32 to -6 and 6 to 32A. It would be extremely useful to command discharge from homeassistant in this manner and allow automation with imported agile tariffs.

NUMBER_TYPES: dict[str, WallboxNumberEntityDescription] = {
    CONF_MAX_CHARGING_CURRENT_KEY: WallboxNumberEntityDescription(
        key=CONF_MAX_CHARGING_CURRENT_KEY,
        name="Max. Charging Current",
        min_value=6,
    ),
}

**Comment by hesselonline** [comment]
Hi, I understand your point, don't know of a valid solution though. Can you create a issue for it at the homeassistant git:
https://github.com/home-assistant/core/issues

I will think of a possible fix in the meantime

This custom version/repo is no longer being used
