### ISSUE TITLE
Missing "version" within "manifest.json"

### ISSUE THREAD

**Issue by bslefevre** [hesselonline/wallbox#4]
`WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'wallbox'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'wallbox'`

By adding `"version": "1.0.0"` to your manifest.json it will fix that.

If you want me to do it you can create a branch and I will push the code and you can review the PR

**Comment by bslefevre** [comment]
@hesselonline the June update will be here before you know it!

**Comment by hesselonline** [comment]
Hmm, you sound like my mother with that last comment ;-), I merged the PR of @adebree -> i think that solves your issue as well.

**Comment by bslefevre** [comment]
@hesselonline is it possible to add the wallbox configuration twice with other credentials so my wife can also use HASS instead of the Wallbox app?

**Comment by bslefevre** [comment]
Excellent, thank you!
